### ISSUE TITLE
Diff Viewing broken

### ISSUE THREAD

**Issue by BJClark** [laullon/gitx#110]
One of my favorite features of GitX is the ability to pipe  `git diff` output to gitx and have a nice diff view. This is broken in this fork and seems to just display a plain text output of the diff.

**Comment by elia** [comment]
I have the same bug, @daniele-m has this problem too

**Comment by elia** [comment]
Related to #3?

**Comment by marnen** [comment]
Confirmed for me. GitX 0.8.4, Mac OS X 10.8.4. Help?

**Comment by marchyman** [comment]
On Jun 28, 2013, at 7:44 AM, Marnen Laibow-Koser notifications@github.com wrote:

> Confirmed for me. GitX 0.8.4, Mac OS X 10.8.4. Help?

gitx compiled from commit bff6661f40d1c47e400 works for me on 10.8.4.  No
issues viewing diffs.  I've been using that version since the end of last July.

I usually build from the command line

  xcodebuild -configuration Release -target GitX

Marc

**Comment by marnen** [comment]
@BJClark I didn't know you could pipe diffs to GitX. I usually use `gitx --diff`, which takes the same arguments as `git diff`.

@marchyman Trying a build from that commit now. Thanks.

**Comment by marnen** [comment]
@marchyman Not working for me. Same display bug.

**Comment by marnen** [comment]
@BJClark Was this fixed? If so, in which build?
