### ISSUE TITLE
Can't copy code from Staged files

### ISSUE THREAD

**Issue by firedev** [laullon/gitx#123]
Please make it so we can copy code from Staged files. (Without line numbers please, see #111)

**Comment by ghost** [comment]
+1

**Comment by jspiro** [comment]
I'm seeing an issue since the command-click staging is having serious problems -- I cmd-click a single line and then it replaces the line with another line a few lines below it, everything gets jumbled around even if I adjust the context to be full or minimal.

On a separate note, cmd-click staging should be a preference, or inverted so holding command lets you select text and clicking works as it always has -- it selects a line for staging -- as that is the primary function of gitx (for me).

I do <3 gitx or I wouldn't go to the source to complain ;-) (I even learned the minimal amount of objc to make a small patch of my own... but it was rough seas)
