### ISSUE TITLE
Error when staging/ unstaging a line

### ISSUE THREAD

**Issue by lacco** [laullon/gitx#29]
Staging/ unstaging lines causes the following error:

Index Operation Failed
Applying patch failed with return value 128. Error: fatal: corrupt patch at line 28

Git version: 1.7.4.4

**Comment by laullon** [comment]
I can't reproduce it, where do you see that error?

**Comment by harawata** [comment]
In my case, this happens when the file has no newline at the end.

When I try to stage lines in terminal with git command, it treats the '\ No newline at end of file' as the last hunk.
And it seems that I have to stage the last hunk or the entire staging fails with the 'patch failed' error.

I am using GitX (L) 0.8.4

**Comment by vguerci** [comment]
Confirming this issue.
Thanks harawata for identifying the newline at end cause, now I have a workaround :)
I always wondered why newline at end are recommended, now I know.
