### ISSUE TITLE
SSH Remote Login with incorrect text

### ISSUE THREAD

**Issue by jelovirt** [laullon/gitx#47]
Versions 0.8.1 and 0.8.2 beta keep prompting for SSH Remote Login with text "???? poipoi". OS X locale is English, not other text comes out like this.

![Screen capture](http://media.disqus.com/uploads/mediaupload/tmp/e462aca8327107901a03e89313070c5ba0af58fefe46a4868149f73d/original.jpg)

**Comment by RomainMuller** [comment]
It looks a lot like gitx_ask_passwd gets called with no arguments... I see what code path generates what you see, but I don't see how to get it fixed just yet...

**Comment by jelovirt** [comment]
I don't know if this makes any difference, but when I open a repository, the SSH remote login pops up _without_ asking to fetch origin.

**Comment by laullon** [comment]
Can you test with this binary?

https://github.com/downloads/laullon/gitx/GitX_v082ga.zip

**Comment by jelovirt** [comment]
Tested with the binary. When I launch GitX and open a repository, after few seconds it pops up a dialog

![dialog](http://elovirta.com/tmp/gitxprompt.png)

If I try to fetch a remote repostory, I get the same dialog.

**Comment by laullon** [comment]
OK. That's what I expected.
Send me your system.log

Thanks.

**Comment by dak180** [comment]
I assume that this is for decrypting a key for use.
Rather than having your own way of doing this would it not be better to hand this off [to the system (this works the same way on 10.5 and 10.6)](http://www.dribin.org/dave/blog/archives/2007/11/28/ssh_agent_leopard/)?
I do find that I need to run `launchctl setenv SSH_AUTH_SOCK ${SSH_AUTH_SOCK}` in my `~/.profile` for it to be visible to most normal applications; surely doing an equivalent operation would be easier and less prone to breaking?

**Comment by laullon** [comment]
Yeah, but this only solve private keys password problem, and not the http

**Comment by dak180** [comment]
True enough.
Still, I hope it shrinks the problem space for you.

**Comment by laullon** [comment]
I'm working on a new ask_password
